sudo: true
os: osx
language: node_js
osx_image: xcode8.2
node_js:
  - '8'
  - '10'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - brew update
  - brew install graphicsmagick
#  - brew outdated graphicsmagick || brew upgrade graphicsmagick
